//! A deterministic, controllable [`EntropySource`] for tests.
//!
//! Exposed to integration tests via the `testing` Cargo feature (see
//! `Cargo.toml`). The harness lets tests:
//! - enqueue specific byte sequences to be returned by `collect`,
//! - flip availability on the fly,
//! - force the next call to fail once,
//! - observe how many times `collect` was called.
//!
//! It is **not** a CSPRNG substitute. Bytes are either caller-supplied or
//! generated by a deterministic LCG seeded at construction time; do not
//! use this type outside of tests and benches.

#![cfg(any(test, feature = "testing"))]

use std::collections::VecDeque;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::Mutex;

use crate::entropy::EntropySource;
use crate::error::Error;

/// Controllable entropy source for tests.
pub struct MockEntropySource {
    name: String,
    description: String,
    priority: u32,
    source_type: &'static str,
    queue: Mutex<VecDeque<Vec<u8>>>,
    available: AtomicBool,
    fail_next: AtomicBool,
    calls: AtomicU64,
    lcg_seed: Mutex<u64>,
    use_lcg: AtomicBool,
}

impl MockEntropySource {
    /// Create a new source identified by `name` at the given priority.
    /// Starts available, with an empty queue, and LCG fallback disabled.
    pub fn new(name: &str, priority: u32) -> Self {
        Self {
            name: name.to_string(),
            description: format!("mock: {name}"),
            priority,
            source_type: "software",
            queue: Mutex::new(VecDeque::new()),
            available: AtomicBool::new(true),
            fail_next: AtomicBool::new(false),
            calls: AtomicU64::new(0),
            lcg_seed: Mutex::new(0x0123_4567_89ab_cdef),
            use_lcg: AtomicBool::new(false),
        }
    }

    /// Classify this source (for `source_type` on the trait).
    pub fn with_type(mut self, ty: &'static str) -> Self {
        self.source_type = ty;
        self
    }

    /// Enable a seeded-LCG fallback so `collect` succeeds even when the
    /// queue is empty. Output is deterministic for a given seed.
    pub fn with_lcg(self, seed: u64) -> Self {
        *self.lcg_seed.lock().expect("lcg_seed mutex") = seed;
        self.use_lcg.store(true, Ordering::Release);
        self
    }

    /// Enqueue a specific byte sequence to be returned on the next
    /// successful `collect` call.
    pub fn push_bytes(&self, bytes: &[u8]) {
        self.queue
            .lock()
            .expect("queue mutex")
            .push_back(bytes.to_vec());
    }

    /// Flip availability to false. Cascade tests use this to verify
    /// fallback-to-next-source behavior.
    pub fn set_unavailable(&self) {
        self.available.store(false, Ordering::Release);
    }

    /// Flip availability back to true.
    pub fn set_available(&self) {
        self.available.store(true, Ordering::Release);
    }

    /// Make the next single `collect` call return an error, then revert.
    pub fn set_fail_next(&self) {
        self.fail_next.store(true, Ordering::Release);
    }

    /// Number of times `collect` has been invoked (including failures).
    pub fn call_count(&self) -> u64 {
        self.calls.load(Ordering::Acquire)
    }
}

impl EntropySource for MockEntropySource {
    fn name(&self) -> &str {
        &self.name
    }

    fn description(&self) -> &str {
        &self.description
    }

    fn priority(&self) -> u32 {
        self.priority
    }

    fn source_type(&self) -> &str {
        self.source_type
    }

    fn is_available(&self) -> bool {
        self.available.load(Ordering::Acquire)
    }

    fn collect(&self, count: usize) -> Result<Vec<u8>, Error> {
        self.calls.fetch_add(1, Ordering::AcqRel);

        if self.fail_next.swap(false, Ordering::AcqRel) {
            return Err(Error::NoEntropy(format!(
                "mock source {}: fail_next triggered",
                self.name
            )));
        }

        if !self.available.load(Ordering::Acquire) {
            return Err(Error::NoEntropy(format!(
                "mock source {}: marked unavailable",
                self.name
            )));
        }

        // Prefer a queued buffer; pad/truncate to `count` as required.
        if let Some(mut buf) = self.queue.lock().expect("queue mutex").pop_front() {
            buf.resize(count, 0);
            return Ok(buf);
        }

        if self.use_lcg.load(Ordering::Acquire) {
            let mut seed = self.lcg_seed.lock().expect("lcg_seed mutex");
            let mut out = Vec::with_capacity(count);
            for _ in 0..count {
                *seed = seed
                    .wrapping_mul(6364136223846793005)
                    .wrapping_add(1442695040888963407);
                out.push((*seed >> 56) as u8);
            }
            return Ok(out);
        }

        Err(Error::NoEntropy(format!(
            "mock source {}: no queued bytes and LCG disabled",
            self.name
        )))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn push_then_collect_returns_queued() {
        let s = MockEntropySource::new("q", 1);
        s.push_bytes(&[1, 2, 3, 4]);
        let got = s.collect(4).expect("collect ok");
        assert_eq!(got, vec![1, 2, 3, 4]);
        assert_eq!(s.call_count(), 1);
    }

    #[test]
    fn set_unavailable_makes_collect_fail() {
        let s = MockEntropySource::new("u", 1);
        s.set_unavailable();
        assert!(!s.is_available());
        assert!(s.collect(8).is_err());
    }

    #[test]
    fn set_fail_next_fires_once() {
        let s = MockEntropySource::new("f", 1).with_lcg(0);
        s.set_fail_next();
        assert!(s.collect(4).is_err());
        // Next call reverts to normal behavior.
        assert!(s.collect(4).is_ok());
    }

    #[test]
    fn lcg_fallback_deterministic() {
        let s1 = MockEntropySource::new("a", 1).with_lcg(42);
        let s2 = MockEntropySource::new("b", 1).with_lcg(42);
        assert_eq!(
            s1.collect(32).expect("ok"),
            s2.collect(32).expect("ok"),
            "same seed must produce identical output"
        );
    }

    #[test]
    fn queue_padded_to_requested_count() {
        let s = MockEntropySource::new("pad", 1);
        s.push_bytes(&[0x55]);
        let got = s.collect(4).expect("ok");
        assert_eq!(got, vec![0x55, 0, 0, 0]);
    }

    #[test]
    fn queue_truncated_to_requested_count() {
        let s = MockEntropySource::new("trunc", 1);
        s.push_bytes(&[1, 2, 3, 4, 5, 6, 7, 8]);
        let got = s.collect(3).expect("ok");
        assert_eq!(got, vec![1, 2, 3]);
    }

    #[test]
    fn call_count_increments_even_on_failure() {
        let s = MockEntropySource::new("c", 1);
        s.set_unavailable();
        let _ = s.collect(1);
        let _ = s.collect(1);
        assert_eq!(s.call_count(), 2);
    }

    #[test]
    fn source_type_defaults_to_software() {
        let s = MockEntropySource::new("t", 1);
        assert_eq!(s.source_type(), "software");
        let s2 = MockEntropySource::new("t2", 1).with_type("hardware");
        assert_eq!(s2.source_type(), "hardware");
    }
}
